name: parameter-fitting
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - networkit=10.1
  - cython
  - filelock
  - tqdm
  - pathos
  - pip
  # Support for girg
  - cmake=3.15
  - powerlaw